//API users
GET http://localhost:2000/getUser

###
GET http://localhost:2000/getUserbyEmail/123@gmail.com

###
POST http://localhost:2000/api/v1/users/login
Content-Type: application/json

{
      "password": "cek1234",
      "email": "bagus@gmail.com"
}


###
POST http://localhost:2000/api/v1/users/register
Content-Type: application/json

{
    "email": "tes1@gmail.com",
    "password": "tes"
}

//API reflections
###
GET http://localhost:2000/api/v1/reflections
x-access-token:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjYwMTc5MDV9.jZM_7O4CklYsNjuaFiuUIGvXwhejdJvKIBuJbH2IDzU

###
POST http://localhost:2000/api/v1/reflections
Content-Type: application/json
x-access-token:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjYwMTQwODF9.VAAr4d_6C35UfWLxF18uggliKhoOUcCL1GPEYWon6Vg

{
   "success" : "okee ke 22",
   "low_point": "okee",
   "take_away": "okee", 
   "owner_id": "1",
   "created_date": "",
   "modified_date": ""
}

###
PUT http://localhost:2000/api/v1/reflections/27
Content-Type: application/json
x-access-token:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjYwMTQwODF9.VAAr4d_6C35UfWLxF18uggliKhoOUcCL1GPEYWon6Vg

{
   "success" : "okee ke 22",
   "low_point": "edit 22",
   "take_away": "edit 22", 
   "owner_id": "12",
   "created_date": "",
   "modified_date": ""
}

###
DELETE http://localhost:2000/api/v1/reflections/27
x-access-token:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjYwMTQwODF9.VAAr4d_6C35UfWLxF18uggliKhoOUcCL1GPEYWon6Vg
